version: "3"
services:
  nginx:
    container_name: proxy
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  database:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  server:
    container_name: taxi-back
    depends_on:
      - database
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    # restart: always

  client:
    container_name: taxi-front
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
