version: "3"
services:
  nginx:
    container_name: proxy
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  database:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    #port=27017

  server:
    container_name: taxi-back
    depends_on:
      - database
    build:
      context: ./server/
      dockerfile: Dockerfile
    restart: always
    #port=5001

  client:
    container_name: taxi-front
    build:
      context: ./client/
      dockerfile: Dockerfile
    restart: always
    #port=3000
