version: "3"
services:
  nginx:
    container_name: proxy
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  database:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    #port=27017

  server:
    container_name: taxi-back
    depends_on:
      - database
    image: ghcr.io/snaoyam/2023-winter-wheel-assignment/server:latest
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=${SERVER_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${SERVER_AWS_SECRET_ACCESS_KEY}
      - DB_PATH=${SERVER_DB_PATH}
      - FRONT_URL=${SERVER_FRONT_URL}
      - SESSION_KEY=${SERVER_SESSION_KEY}
      - SPARCSSSO_CLIENT_ID=${SERVER_SPARCSSSO_CLIENT_ID}
      - SPARCSSSO_CLIENT_KEY=${SERVER_SPARCSSSO_CLIENT_KEY}
    #port=5001

  client:
    container_name: taxi-front
    image: ghcr.io/snaoyam/2023-winter-wheel-assignment/client:latest
    restart: always
    environment:
      - REACT_APP_BACK_URL=${CLIENT_REACT_APP_BACK_URL}
    #port=3000

volumes:
  mongo-data: