name: build-image-server
on:
  push:
    branches:
      - main
jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        path: ./server
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image and Push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: |
            "ghcr.io/${{ github.actor }}/taxi-server:${{ github.ref_name }}"
            "ghcr.io/${{ github.actor }}/taxi-server:latest"