name: Deploy container image to produnction server
on:
  workflow_run:
    workflows:
      - build-image-client
      # - build-image-server
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          include:
            - SERVER_*
            - CLIENT_*
      - name: pull image and restart the container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          port: ${{ secrets.PROD_PORT }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          script_stop: true
          script: |
            cd $${{ secrets.PROD_PATH }}
            docker compose --file ./docker-compose.yml pull
            docker compose --file ./docker-compose.yml --project-name taxi up --detach
